### ISSUE TITLE
How do I know which one is selected, and how do I set which one is selected on default?

### ISSUE THREAD

**Issue by yannickE** [Kaopiz/android-segmented-control#46]
Hi, 
basically the question is already in the title. But here again: How do I tell my app that the first or second one is selected, and how do I set which one is selected when you enter the activity?

Cheers,
Yannick E.

**Comment by comalex** [comment]
SegmentedGroup Inherited RadioGroup, so you can use all features of RadioGroup.

**Comment by DarkRockman** [comment]
Quick answer, use xml property android:checkedButton on your layout to set the default by it's id or the java method check(int id)

**Comment by tuanna-hsp** [comment]
You can use setOnCheckedChangeListener() to monitor selected state.

**Comment by myJarvis** [comment]
i am setting checked false to all radio buttons on clicking of an another view , again i am clicking one radio button and want to make it checked(highlight) and adding programatically setChecked true also but it is not highlighting , and if i am selecting another radio button that is highlighting , and after selecting another radio button if i am selecting that radio button that is also becoming highlighted , what to do reply soon

**Comment by myJarvis** [comment]
i am posting demo project also check this and reply fast 
[IssueDemo.zip](https://github.com/Kaopiz/android-segmented-control/files/179562/IssueDemo.zip)

**Comment by mxn21** [comment]
@myJarvis  you can use  segmentedGroup.clearChecked()  instead of setChecked(false); like this :

`@OnClick(R.id.buttonMakeSelectionFalse)
    public void buttonMakeSelectionFalseClicked() {

//        one.setChecked(false);
//        two.setChecked(false);
//        three.setChecked(false);
//        four.setChecked(false);
        segmentedGroup.clearCheck();
        helloTextView.setVisibility(View.VISIBLE);
    }`

**Comment by tuanna-hsp** [comment]
Have you solved your problem yet?

**Comment by myJarvis** [comment]
yes solved thanks for asking

**Comment by myJarvis** [comment]
hey bro one confusion is there , i need your little help

**Comment by myJarvis** [comment]
in the segmented group library , i want to put radiobuttons in one segment
in horizontal fashion is it possible to do that

**Comment by bibinjacobpulickal** [comment]
"use xml property android:checkedButton on your layout to set the default by it's id" this was said above and I did exactly the same but, RadioButton is created after this is being called. So, we get "Error: No resource found that matches the given name". How do I overcome this? Maybe it's bit obvious but I'm a bit new. Also, I know that there is a programmatic approach for now I'm gonna use that.
