### ISSUE TITLE
Can We Create one Segmented Group Programatically

### ISSUE THREAD

**Issue by myJarvis** [Kaopiz/android-segmented-control#52]
Can We Create one Segmented Group Programatically with n number of radio button inside

**Comment by tuanna-hsp** [comment]
@myJarvis Basically SegmentedGroup is a RadioGroup - which is inherited from LinearLayout, so you can do anything the RadioGroup can provide.
`SegmentedGroup group = new SegmentedGroup(SampleActivity.this);
 RadioButton button = new RadioButton(SampleActivity.this);
 group.addView(button);`

**Comment by myJarvis** [comment]
ya its done already thanks

**Comment by elod91** [comment]
@tuanna-hsp That's not working properly. Can you post a full sample adding the RadioButtons to the segmented group with the style and everything? Using the code sample you've provided just adds simple RadioButtons without borders or anything.

**Comment by biokys** [comment]
You have to call segmentedGroup.updateBackground() method after adding view.
